# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 19:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, choices=[('Lab-1', 'Lab 1'), ('Lab-5', 'Lab 5'), ('CCF', 'CCF')], max_length=30)),
                ('device_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('vendor_info', models.CharField(blank=True, max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_check', models.DateField(blank=True)),
                ('issues_count', models.IntegerField(default=0)),
                ('buy_price', models.IntegerField(null=True)),
                ('current_price', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('issue', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('resolved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student', models.BooleanField(default=True)),
                ('is_lab_staff', models.BooleanField(default=False)),
                ('is_technician', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location'),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
