# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170422_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Please enter value slugified. Eg: lab-04, CCF', max_length=50),
        ),
    ]
